-- Generated by Mocodo 4.2.4

CREATE TABLE Appartient_a (
  PRIMARY KEY (id_point, Livre_id, id_division),
  id_point    VARCHAR(42) NOT NULL,
  Livre_id    VARCHAR(42) NOT NULL,
  id_division VARCHAR(42) NOT NULL
);

CREATE TABLE Contre_indications (
  PRIMARY KEY (id_contre_indication),
  id_contre_indication    VARCHAR(42) NOT NULL,
  point_id                VARCHAR(42),
  nom_contre_indication   VARCHAR(42),
  texte_contre_indication VARCHAR(42)
);

CREATE TABLE Division (
  PRIMARY KEY (id_division),
  id_division  VARCHAR(42) NOT NULL,
  nom_division VARCHAR(42)
);

CREATE TABLE Efficacite_sur_les_meridiens (
  PRIMARY KEY (id_efficacite),
  id_efficacite VARCHAR(42) NOT NULL,
  id_point      VARCHAR(42),
  id_meridien   VARCHAR(42),
  efficacite    VARCHAR(42)
);

CREATE TABLE Fait_partie (
  PRIMARY KEY (id_point, Livre_id, famille_id),
  id_point   VARCHAR(42) NOT NULL,
  Livre_id   VARCHAR(42) NOT NULL,
  famille_id VARCHAR(42) NOT NULL
);

CREATE TABLE Familles_de_points (
  PRIMARY KEY (famille_id),
  famille_id  VARCHAR(42) NOT NULL,
  nom_famille VARCHAR(42)
);

CREATE TABLE Indications_primaires (
  PRIMARY KEY (id_indication_primaire),
  id_indication_primaire    VARCHAR(42) NOT NULL,
  point_id                  VARCHAR(42),
  nom_indication_primaire   VARCHAR(42),
  texte_indication_primaire VARCHAR(42)
);

CREATE TABLE Indications_secondaires (
  PRIMARY KEY (id_indication_secondaire),
  id_indication_secondaire    VARCHAR(42) NOT NULL,
  point_id                    VARCHAR(42),
  nom_indication_secondaire   VARCHAR(42),
  texte_indication_secondaire VARCHAR(42)
);

CREATE TABLE Livre (
  PRIMARY KEY (Livre_id),
  Livre_id       VARCHAR(42) NOT NULL,
  Titre          VARCHAR(42),
  Suite_du_titre VARCHAR(42),
  Auteur         VARCHAR(42),
  Autres_auteurs VARCHAR(42),
  ISBN           VARCHAR(42),
  Edition        VARCHAR(42),
  Annee          VARCHAR(42)
);

CREATE TABLE Localisation (
  PRIMARY KEY (ID_localisation),
  ID_localisation         VARCHAR(42) NOT NULL,
  point_id                VARCHAR(42),
  desc_anatomique         VARCHAR(42),
  langue_localisation     VARCHAR(42),
  image_localisation      VARCHAR(42),
  image_ligne_de_puncture VARCHAR(42),
  note1                   VARCHAR(42),
  note2                   VARCHAR(42),
  id_point                VARCHAR(42) NOT NULL,
  Livre_id                VARCHAR(42) NOT NULL
);

CREATE TABLE Mecanismes (
  PRIMARY KEY (id_mecanisme),
  id_mecanisme  VARCHAR(42) NOT NULL,
  nom_mecanisme VARCHAR(42),
  id_point      VARCHAR(42) NOT NULL
);

CREATE TABLE Mecanismes_explications (
  PRIMARY KEY (id_point),
  id_point     VARCHAR(42) NOT NULL,
  id_mecanisme VARCHAR(42)
);

CREATE TABLE Methode_equilibre (
  PRIMARY KEY (id_methode_equilibre),
  id_methode_equilibre    VARCHAR(42) NOT NULL,
  point_id                VARCHAR(42),
  nom_equilibrage         VARCHAR(42),
  description_equilibrage VARCHAR(42)
);

CREATE TABLE Points (
  PRIMARY KEY (id_point, Livre_id),
  id_point                 VARCHAR(42) NOT NULL,
  Livre_id                 VARCHAR(42) NOT NULL,
  famille_id               VARCHAR(42),
  nom_pinyin_accent        VARCHAR(42),
  nom_pinyin_sans_accent   VARCHAR(42),
  nom_chinois_simplifie    VARCHAR(42),
  nom_chinois_traditionnel VARCHAR(42),
  nom_francais             VARCHAR(42),
  nom_anglais              VARCHAR(42),
  nom_espagnol             VARCHAR(42),
  division                 VARCHAR(42),
  autorisation_saignee     VARCHAR(42),
  aiguilles_absolues       VARCHAR(42),
  aiguilles_resolution     VARCHAR(42),
  id_protocole             VARCHAR(42) NOT NULL,
  id_efficacite            VARCHAR(42) NOT NULL,
  id_remarque              VARCHAR(42) NOT NULL,
  id_contre_indication     VARCHAR(42) NOT NULL,
  id_indication_secondaire VARCHAR(42) NOT NULL,
  id_situation             VARCHAR(42) NOT NULL,
  id_methode_equilibre     VARCHAR(42) NOT NULL,
  id_point_2               VARCHAR(42) NOT NULL,
  id_indication_primaire   VARCHAR(42) NOT NULL
);

CREATE TABLE Protocoles (
  PRIMARY KEY (id_protocole),
  id_protocole          VARCHAR(42) NOT NULL,
  point_id              VARCHAR(42),
  nom_protocole         VARCHAR(42),
  description_protocole VARCHAR(42)
);

CREATE TABLE Remarques (
  PRIMARY KEY (id_remarque),
  id_remarque      VARCHAR(42) NOT NULL,
  id_point         VARCHAR(42),
  nom_remarque     VARCHAR(42),
  contenu_remarque VARCHAR(42)
);

CREATE TABLE Situation_anatomique (
  PRIMARY KEY (id_situation),
  id_situation        VARCHAR(42) NOT NULL,
  id_point            VARCHAR(42),
  nom_muscles         VARCHAR(42),
  nom_vascularisation VARCHAR(42),
  nom_innervation     VARCHAR(42),
  nom_shengjing       VARCHAR(42)
);

CREATE TABLE Utilise (
  PRIMARY KEY (id_point, Livre_id_1, Livre_id_2),
  id_point   VARCHAR(42) NOT NULL,
  Livre_id_1 VARCHAR(42) NOT NULL,
  Livre_id_2 VARCHAR(42) NOT NULL
);

ALTER TABLE Appartient_a ADD FOREIGN KEY (id_division) REFERENCES Division (id_division);
ALTER TABLE Appartient_a ADD FOREIGN KEY (id_point, Livre_id) REFERENCES Points (id_point, Livre_id);

ALTER TABLE Fait_partie ADD FOREIGN KEY (famille_id) REFERENCES Familles_de_points (famille_id);
ALTER TABLE Fait_partie ADD FOREIGN KEY (id_point, Livre_id) REFERENCES Points (id_point, Livre_id);

ALTER TABLE Localisation ADD FOREIGN KEY (id_point, Livre_id) REFERENCES Points (id_point, Livre_id);

ALTER TABLE Mecanismes ADD FOREIGN KEY (id_point) REFERENCES Mecanismes_explications (id_point);

ALTER TABLE Points ADD FOREIGN KEY (id_indication_primaire) REFERENCES Indications_primaires (id_indication_primaire);
ALTER TABLE Points ADD FOREIGN KEY (id_point_2) REFERENCES Mecanismes_explications (id_point);
ALTER TABLE Points ADD FOREIGN KEY (id_methode_equilibre) REFERENCES Methode_equilibre (id_methode_equilibre);
ALTER TABLE Points ADD FOREIGN KEY (id_situation) REFERENCES Situation_anatomique (id_situation);
ALTER TABLE Points ADD FOREIGN KEY (id_indication_secondaire) REFERENCES Indications_secondaires (id_indication_secondaire);
ALTER TABLE Points ADD FOREIGN KEY (id_contre_indication) REFERENCES Contre_indications (id_contre_indication);
ALTER TABLE Points ADD FOREIGN KEY (id_remarque) REFERENCES Remarques (id_remarque);
ALTER TABLE Points ADD FOREIGN KEY (id_efficacite) REFERENCES Efficacite_sur_les_meridiens (id_efficacite);
ALTER TABLE Points ADD FOREIGN KEY (id_protocole) REFERENCES Protocoles (id_protocole);

ALTER TABLE Utilise ADD FOREIGN KEY (Livre_id_2) REFERENCES Livre (Livre_id);
ALTER TABLE Utilise ADD FOREIGN KEY (id_point, Livre_id_1) REFERENCES Points (id_point, Livre_id);

